[package]
edition = "2018"
name = "rust_practice_actix-web"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.2.0"
actix-web = "3.3.2"
chrono = {version = "0.4.19", features = ["serde"]}
derive-new = "0.5.9"
env_logger = "0.8.3"
log = "0.4.14"
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
rusqlite = {version = "0.25.0", features = ["chrono", "uuid"]}
serde = {version = "1.0.125", features = ["derive"]}
uuid = {version = "0.8.2", features = ["serde", "v4"]}
